# Generated by Django 5.0.12 on 2026-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
