# Generated by Django 5.0.12 on 2025-11-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_key', '0003_keyregenerationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeypair',
            name='private_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
