# Generated by Django 5.0.12 on 2025-10-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('plan',), name='unique_default_price_per_plan'),
        ),
    ]
