# Generated by Django 5.0.12 on 2025-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_planprice_unique_default_price_per_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method_type',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('mobile_money', 'Mobile Money'), ('wallet', 'Wallet'), ('other', 'Other')], max_length=24),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual/Billing Admin')], max_length=24),
        ),
    ]
