# Generated by Django 5.0.12 on 2025-10-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_stripeeventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_upgrade', models.BooleanField(default=True)),
                ('allow_downgrade', models.BooleanField(default=True)),
                ('auto_charge_on_renewal', models.BooleanField(default=True)),
                ('prorate_on_upgrade', models.BooleanField(default=True)),
                ('prorate_on_downgrade', models.BooleanField(default=False)),
                ('downgrade_effect', models.CharField(choices=[('immediate', 'Immediate Switch'), ('end_of_period', 'After Current Period')], default='end_of_period', help_text='Defines when a downgrade takes effect.', max_length=20)),
                ('upgrade_effect', models.CharField(choices=[('immediate', 'Immediate Access'), ('next_cycle', 'Next Billing Cycle')], default='immediate', help_text='Defines when an upgrade takes effect.', max_length=20)),
                ('refund_policy', models.CharField(choices=[('none', 'No Refunds'), ('partial', 'Prorated Refunds'), ('full', 'Full Refunds')], default='partial', help_text='Defines how refunds are handled on downgrade/cancel.', max_length=20)),
                ('default_provider', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual')], default='stripe', max_length=30)),
                ('enable_multiple_gateways', models.BooleanField(default=True)),
                ('fallback_provider', models.CharField(blank=True, help_text='Optional fallback if the default provider fails.', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Setting',
                'verbose_name_plural': 'Subscription Settings',
            },
        ),
    ]
