# Generated by Django 5.0.12 on 2025-10-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptionsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionsetting',
            name='fallback_provider',
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='downgrade_effect',
            field=models.CharField(choices=[('immediate', 'Immediate Switch'), ('end_of_period', 'After Current Period')], default='end_of_period', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='refund_policy',
            field=models.CharField(choices=[('none', 'No Refunds'), ('partial', 'Prorated Refunds'), ('full', 'Full Refunds')], default='partial', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='upgrade_effect',
            field=models.CharField(choices=[('immediate', 'Immediate Access'), ('next_cycle', 'Next Billing Cycle')], default='immediate', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower = higher priority')),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('additional_settings', models.JSONField(blank=True, null=True)),
                ('subscription_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='subscriptions.subscriptionsetting')),
            ],
            options={
                'verbose_name': 'Payment Provider Setting',
                'verbose_name_plural': 'Payment Provider Settings',
                'ordering': ['priority'],
                'unique_together': {('subscription_setting', 'provider')},
            },
        ),
    ]
