# Generated by Django 5.0.12 on 2025-10-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_subscriptionsetting_fallback_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprovidersetting',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='paymentprovidersetting',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='paymentprovidersetting',
            name='webhook_secret',
        ),
        migrations.AddField(
            model_name='paymentprovidersetting',
            name='cancel_url',
            field=models.URLField(blank=True, help_text='Redirect if user cancels payment'),
        ),
        migrations.AddField(
            model_name='paymentprovidersetting',
            name='success_url',
            field=models.URLField(blank=True, help_text='Redirect after successful payment'),
        ),
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='additional_settings',
            field=models.JSONField(blank=True, help_text='Optional lightweight configuration like country, currency, or API version.', null=True),
        ),
    ]
