# Generated by Django 5.0.12 on 2025-10-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_paymentprovidersetting_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='additional_settings',
            field=models.JSONField(blank=True, help_text='Optional configuration for provider-specific settings (e.g., currency, region, webhook preferences, or custom headers).', null=True),
        ),
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='cancel_url',
            field=models.URLField(blank=True, help_text='Frontend URL users are redirected to if they cancel a payment.'),
        ),
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Enable or disable this provider globally. Disabled providers won't process payments."),
        ),
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Defines provider priority. Lower numbers mean higher preference when multiple gateways are enabled.'),
        ),
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual')], help_text='The payment provider this configuration applies to.', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='subscription_setting',
            field=models.ForeignKey(help_text='The global subscription setting this provider configuration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='subscriptions.subscriptionsetting'),
        ),
        migrations.AlterField(
            model_name='paymentprovidersetting',
            name='success_url',
            field=models.URLField(blank=True, help_text='Frontend URL users are redirected to after a successful payment.'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='allow_downgrade',
            field=models.BooleanField(default=True, help_text='If enabled, users can downgrade to a lower-tier plan (e.g., from Pro to Basic).'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='allow_upgrade',
            field=models.BooleanField(default=True, help_text='If enabled, users can upgrade to a higher-tier plan (e.g., from Basic to Pro).'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='auto_charge_on_renewal',
            field=models.BooleanField(default=True, help_text='Automatically charge users when their subscription renews. Disable for manual billing cycles.'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when this setting record was created.'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='default_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('manual', 'Manual')], default='stripe', help_text='Select the default payment provider for new subscriptions.', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='downgrade_effect',
            field=models.CharField(choices=[('immediate', 'Immediate Switch'), ('end_of_period', 'After Current Period')], default='end_of_period', help_text="Defines when a downgrade takes effect — either immediately or after the user's current billing period ends.", max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='enable_multiple_gateways',
            field=models.BooleanField(default=True, help_text='Allow the system to use more than one payment gateway (e.g., Stripe + Paystack).'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='prorate_on_downgrade',
            field=models.BooleanField(default=False, help_text='If enabled, users downgrading mid-cycle receive proportional credit for unused time.'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='prorate_on_upgrade',
            field=models.BooleanField(default=True, help_text='If enabled, users upgrading mid-cycle are charged only for the remaining time proportionally.'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='refund_policy',
            field=models.CharField(choices=[('none', 'No Refunds'), ('partial', 'Prorated Refunds'), ('full', 'Full Refunds')], default='partial', help_text='Determines how refunds are handled during cancellations or downgrades: no refund, partial/prorated, or full refund.', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updated when any setting changes.'),
        ),
        migrations.AlterField(
            model_name='subscriptionsetting',
            name='upgrade_effect',
            field=models.CharField(choices=[('immediate', 'Immediate Access'), ('next_cycle', 'Next Billing Cycle')], default='immediate', help_text='Defines when an upgrade takes effect — grant access immediately or defer until the next billing cycle.', max_length=20),
        ),
    ]
