# Generated by Django 5.0.12 on 2025-10-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_paymentprovidersetting_additional_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsetting',
            name='can_cancel',
            field=models.BooleanField(default=True, help_text='If enabled, users can manually cancel their active subscription. If disabled, only admins can cancel or pause a subscription.'),
        ),
        migrations.AddField(
            model_name='subscriptionsetting',
            name='cancel_effect',
            field=models.CharField(choices=[('immediate', 'Immediate Termination'), ('end_of_period', 'After Current Period')], default='end_of_period', help_text='Defines when cancellation takes effect — immediately or after the current billing period ends.', max_length=20),
        ),
    ]
