# Generated by Django 5.0.12 on 2025-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionsetting_can_cancel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprovidersetting',
            name='cancel_url',
        ),
        migrations.RemoveField(
            model_name='paymentprovidersetting',
            name='success_url',
        ),
        migrations.AddField(
            model_name='subscriptionsetting',
            name='cancel_url',
            field=models.URLField(blank=True, help_text='Frontend URL users are redirected to if they cancel a payment.'),
        ),
        migrations.AddField(
            model_name='subscriptionsetting',
            name='success_url',
            field=models.URLField(blank=True, help_text='Frontend URL users are redirected to after a successful payment.'),
        ),
    ]
