# Generated by Django 5.0.12 on 2025-10-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_remove_paymentprovidersetting_cancel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsetting',
            name='allow_free_plan_reuse',
            field=models.BooleanField(default=False, help_text='If enabled, users can subscribe to the free plan multiple times. If disabled, users may only use the free plan once.'),
        ),
    ]
