# Generated by Django 5.0.12 on 2025-10-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionsetting_allow_free_plan_reuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('unpaid', 'Unpaid'), ('unknown', 'Unknown')], default='active', max_length=24),
        ),
    ]
