# Generated by Django 5.0.12 on 2025-10-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsetting',
            name='policy_text',
            field=models.TextField(blank=True, help_text='Automatically generated subscription policy text for users to understand payment rules.'),
        ),
    ]
