# Generated by Django 5.0.12 on 2025-10-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_subscriptionsetting_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
