# Generated by Django 5.0.12 on 2025-10-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccess',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10),
        ),
    ]
